---
- hosts: dbservers
  become: true
  tasks:
    - name: Check for mariaDB
      ansible.builtin.stat:
        path: "/lib/systemd/system/mariadb-server.service"
      register: service_unit

    - name: Install mariaDB
      become: true
      ansible.builtin.apt:
        name: mariadb-server
        state: latest
      when: not service_unit.stat.exists

    - name: Autostart
      ansible.builtin.service:
        name: mariadb
        enabled: true
        state: started
